services:
  mongo_db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  storage:
    image: redis
    volumes:
      - ./data:/data

  counter:
    image: toha62/library-counter:0.0.1
    environment:
      - PORT=3002
      - REDIS_URL=redis://storage
    depends_on:
      - storage

  library:
    build: . 
    volumes:
      - .:/app  
    ports:
      - 80:3000
    environment:
      - PORT=3000      
      - COUNTER_URL=http://counter:3002
      - DB_URL=mongodb://root:example@mongo_db:27017    
    depends_on:      
      - counter
      - mongo_db
